### ISSUE TITLE
Cyber dataset missing

### ISSUE THREAD

**Issue by ddofer** [Featuretools/predict-malicious-cyber-connections#1]
Dataset link/download is missing

**Comment by Seth-Rothschild** [comment]
Nice catch! The data that was used in this demo has been uploaded [to S3](https://s3.amazonaws.com/featuretools-static/CyberFLTenDays.csv) and a link was added to the README. The original data source is [here](https://csr.lanl.gov/data/cyber1/).

**Comment by ddofer** [comment]
Original source citation is even more important ;)
